apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: marr69zks-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: marr69zks-python 
  name: marr69zks-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: marr69zks-python 
